targetScope = 'resourceGroup'

type ResourceNames = {
  @minLength(4)
  logAnalyticsName: string

  @minLength(1)
  applicationInsightsName: string

  @minLength(1)
  keyVaultName: string

  @minLength(3)
  @maxLength(24)
  storageAccountName: string

  @minLength(1)
  managedIdentityName: string

  @minLength(1)
  appServicePlanName: string

  @minLength(1)
  apiAppName: string

  @minLength(1)
  portalAppName: string
}

type RuntimeSecretReference = {
  appSettingName: string
  keyVaultSecretName: string
}

type RuntimeApplicationSetting = {
  name: string
  value: string
}

@description('The PageMaker365 application name for this customer deployment.')
@minLength(1)
param appName string

@description('Hosted deployment environment: dev, staging, or production.')
@allowed([
  'dev'
  'staging'
  'production'
])
param environment string

@description('Azure region for resources.')
@minLength(1)
param location string = resourceGroup().location

@description('Customer Entra tenant ID from the deployment package.')
@minLength(36)
@maxLength(36)
param customerTenantId string = subscription().tenantId

@description('Customer-owned portal Entra application client ID.')
@minLength(36)
@maxLength(36)
param portalClientId string

@description('Customer-owned API Entra application client ID.')
@minLength(36)
@maxLength(36)
param apiClientId string

@description('Customer display name exposed by the portal runtime.')
@minLength(1)
@maxLength(128)
param customerDisplayName string

@description('Customer short name exposed by the portal runtime.')
@minLength(1)
@maxLength(64)
param customerShortName string

@description('Hosted portal runtime environment.')
@allowed([
  'dev'
  'staging'
  'production'
])
param webRuntimeEnvironment string

@description('Exact customer SharePoint origin used by API and portal File Preview policy.')
@minLength(1)
param filePreviewAllowedFrameOrigins string

@description('Resource names generated by the PageMaker365 control-plane deployment export.')
param resourceNames ResourceNames

@description('Secret-name-only App Service references. Values are provisioned separately through a secure ARM parameter.')
param runtimeSecretReferences RuntimeSecretReference[]

@description('Default-disabled package-0.7 runtime-configuration application gate.')
param enableRuntimeConfigurationProjectionV2 bool = false

@description('Exact validated projection-v2 API public settings.')
param apiRuntimeConfigurationPublicSettings RuntimeApplicationSetting[] = []

@description('Exact validated projection-v2 portal public settings.')
param portalRuntimeConfigurationPublicSettings RuntimeApplicationSetting[] = []

@description('Only already-versioned projection-v2 API Key Vault references. Pending license and cursor destinations are excluded.')
param apiRuntimeConfigurationProtectedSettingReferences RuntimeApplicationSetting[] = []

@description('Immutable PageMaker365 runtime release identifier.')
@minLength(1)
@maxLength(128)
param runtimeReleaseId string

@description('Stable semantic PageMaker365 runtime version.')
@minLength(5)
@maxLength(32)
param runtimeVersion string

@description('Signed control-plane deployment export identifier.')
@minLength(1)
@maxLength(256)
param deploymentExportId string

@description('Common tags applied to PageMaker365 resources.')
param tags object = {
  product: 'PageMaker365'
  environment: environment
}

var mergedTags = union(tags, {
  appName: appName
})

var portalDefaultOrigin = 'https://${resourceNames.portalAppName}.azurewebsites.net'

module logAnalytics 'modules/log-analytics.bicep' = {
  name: 'logAnalytics'
  params: {
    name: resourceNames.logAnalyticsName
    location: location
    tags: mergedTags
  }
  dependsOn: [
    appServicePlan
  ]
}

module appInsights 'modules/application-insights.bicep' = {
  name: 'applicationInsights'
  params: {
    name: resourceNames.applicationInsightsName
    location: location
    tags: mergedTags
    workspaceResourceId: logAnalytics.outputs.workspaceResourceId
  }
}

module keyVault 'modules/key-vault.bicep' = {
  name: 'keyVault'
  params: {
    name: resourceNames.keyVaultName
    location: location
    tags: mergedTags
    tenantId: customerTenantId
  }
  dependsOn: [
    appServicePlan
  ]
}

module storage 'modules/storage-account.bicep' = {
  name: 'storageAccount'
  params: {
    name: resourceNames.storageAccountName
    location: location
    tags: mergedTags
  }
  dependsOn: [
    appServicePlan
  ]
}

module managedIdentity 'modules/managed-identity.bicep' = {
  name: 'managedIdentity'
  params: {
    name: resourceNames.managedIdentityName
    location: location
    tags: mergedTags
  }
  dependsOn: [
    appServicePlan
  ]
}

module appServicePlan 'modules/linux-app-service-plan.bicep' = {
  name: 'linuxAppServicePlan'
  params: {
    name: resourceNames.appServicePlanName
    location: location
    tags: mergedTags
  }
}

module apiApp 'modules/api-app-service.bicep' = {
  name: 'apiAppService'
  params: {
    name: resourceNames.apiAppName
    location: location
    tags: mergedTags
    appServicePlanId: appServicePlan.outputs.appServicePlanResourceId
    managedIdentityResourceId: managedIdentity.outputs.managedIdentityResourceId
    applicationInsightsConnectionString: appInsights.outputs.connectionString
    keyVaultUri: keyVault.outputs.keyVaultUri
    keyVaultName: resourceNames.keyVaultName
    runtimeSecretReferences: runtimeSecretReferences
    enableRuntimeConfigurationProjectionV2: enableRuntimeConfigurationProjectionV2
    runtimeConfigurationPublicSettings: apiRuntimeConfigurationPublicSettings
    runtimeConfigurationProtectedSettingReferences: apiRuntimeConfigurationProtectedSettingReferences
    customerTenantId: customerTenantId
    apiClientId: apiClientId
    portalOrigin: portalDefaultOrigin
    filePreviewAllowedFrameOrigins: filePreviewAllowedFrameOrigins
    runtimeReleaseId: runtimeReleaseId
    runtimeVersion: runtimeVersion
    deploymentExportId: deploymentExportId
  }
}

module portalApp 'modules/frontend-app-service.bicep' = {
  name: 'frontendAppService'
  params: {
    name: resourceNames.portalAppName
    location: location
    tags: mergedTags
    appServicePlanId: appServicePlan.outputs.appServicePlanResourceId
    managedIdentityResourceId: managedIdentity.outputs.managedIdentityResourceId
    applicationInsightsConnectionString: appInsights.outputs.connectionString
    apiUrl: apiApp.outputs.apiUrl
    runtimeReleaseId: runtimeReleaseId
    enableRuntimeConfigurationProjectionV2: enableRuntimeConfigurationProjectionV2
    runtimeConfigurationPublicSettings: portalRuntimeConfigurationPublicSettings
    customerTenantId: customerTenantId
    portalClientId: portalClientId
    apiClientId: apiClientId
    runtimeEnvironment: webRuntimeEnvironment
    customerDisplayName: customerDisplayName
    customerShortName: customerShortName
    filePreviewAllowedFrameOrigins: filePreviewAllowedFrameOrigins
  }
}

module keyVaultSecretUserAssignment 'modules/key-vault-role-assignment.bicep' = {
  name: 'keyVaultSecretUserAssignment'
  params: {
    keyVaultName: resourceNames.keyVaultName
    principalResourceId: managedIdentity.outputs.managedIdentityResourceId
    principalId: managedIdentity.outputs.managedIdentityPrincipalId
  }
  dependsOn: [
    keyVault
  ]
}

output appName string = appName
output environment string = environment
output location string = location
output tags object = mergedTags
output apiUrl string = apiApp.outputs.apiUrl
output portalUrl string = portalApp.outputs.portalUrl
output keyVaultUri string = keyVault.outputs.keyVaultUri
output keyVaultResourceId string = keyVault.outputs.keyVaultResourceId
output managedIdentityPrincipalId string = managedIdentity.outputs.managedIdentityPrincipalId
output applicationInsightsConnectionString string = appInsights.outputs.connectionString
output storageAccountId string = storage.outputs.storageAccountResourceId
output logAnalyticsResourceId string = logAnalytics.outputs.workspaceResourceId
output applicationInsightsResourceId string = appInsights.outputs.applicationInsightsResourceId
output applicationInsightsInstrumentationKey string = appInsights.outputs.instrumentationKey
output appServicePlanResourceId string = appServicePlan.outputs.appServicePlanResourceId
output apiAppServiceResourceId string = apiApp.outputs.apiAppServiceResourceId
output portalAppServiceResourceId string = portalApp.outputs.frontendAppServiceResourceId
output managedIdentityResourceId string = managedIdentity.outputs.managedIdentityResourceId
output keyVaultSecretUserRoleAssignmentId string = keyVaultSecretUserAssignment.outputs.roleAssignmentResourceId
