targetScope = 'subscription'

type ResourceNames = {
  logAnalyticsName: string
  applicationInsightsName: string
  keyVaultName: string
  storageAccountName: string
  managedIdentityName: string
  appServicePlanName: string
  apiAppName: string
  portalAppName: string
}

type RuntimeSecretReference = {
  appSettingName: string
  keyVaultSecretName: string
}

@sealed()
type ApiRuntimeConfigurationV2 = {
  API_APP_VERSION: string
  API_ENV: string
  API_HOST: string
  API_CORS_ORIGIN: string[]
  API_ENTRA_TENANT_ID: string
  API_ENTRA_AUDIENCE: string[]
  API_ENTRA_CLIENT_ID: string
  API_GRAPH_SCOPES: string[]
  API_REQUIRED_SCOPES: string[]
  API_SHAREPOINT_SITE_URL: string
  API_SHAREPOINT_UPLOADS_LIBRARY_NAME: string
  API_SHAREPOINT_ISSUES_LIST_NAME: string
  API_TENANT_CONNECTION_ID: string
  API_TENANT_DISPLAY_NAME: string
  PAGEMAKER365_PORTAL_URL: string
  API_LICENSE_PUBLIC_KEY_PEM: string
  API_LICENSE_ENVIRONMENT_KEY: string
  API_LICENSE_RUNTIME_HOSTNAME: string
  API_LICENSE_VALIDATION_GRACE_HOURS: int
  API_LICENSE_VALIDATION_INTERVAL_HOURS: int
  API_AZURE_KEY_VAULT_URL: string
  API_CONNECTOR_EGRESS_REQUIRE_ALLOWLIST: bool
  API_RUNTIME_TRUST_FORWARDED_HOST: bool
  NODE_ENV: string
  PM365_PRODUCT: string
  PM365_DEPLOYMENT_EXPORT_ID: string
  PM365_RUNTIME_RELEASE_ID: string
  PM365_RUNTIME_VERSION: string
  API_FILE_PREVIEW_ALLOWED_FRAME_ORIGINS: string[]
  API_FILE_PREVIEW_DOWNLOAD_POLICY: string
  API_FILE_PREVIEW_SOURCE_FALLBACK_POLICY: string
}

@sealed()
type PortalRuntimeConfigurationV2 = {
  WEB_API_BASE_URL: string
  WEB_ENTRA_CLIENT_ID: string
  WEB_ENTRA_TENANT_ID: string
  WEB_ENTRA_AUTHORITY: string
  WEB_API_SCOPE: string
  WEB_RUNTIME_ENVIRONMENT: string
  WEB_PRODUCT_NAME: string
  WEB_PRODUCT_LOGO_URL: string
  WEB_CUSTOMER_DISPLAY_NAME: string
  WEB_CUSTOMER_SHORT_NAME: string
  WEB_FILE_PREVIEW_ALLOWED_FRAME_ORIGINS: string[]
}

@sealed()
type ApiRuntimeConfigurationVersionedReferencesV2 = {
  DATABASE_URL: string
  API_ENTRA_CLIENT_SECRET: string
}

@description('Dedicated PageMaker365 resource group name.')
@minLength(1)
param resourceGroupName string

@description('The PageMaker365 application name for this customer deployment.')
@minLength(1)
param appName string

@description('Hosted deployment environment: dev, staging, or production.')
@allowed([
  'dev'
  'staging'
  'production'
])
param environment string

@description('Azure region for the resource group and PageMaker365 resources.')
@minLength(1)
param location string

@description('Customer Entra tenant ID from the deployment package.')
@minLength(36)
@maxLength(36)
param customerTenantId string

@description('Customer-owned portal Entra application client ID.')
@minLength(36)
@maxLength(36)
param portalClientId string

@description('Customer-owned API Entra application client ID.')
@minLength(36)
@maxLength(36)
param apiClientId string

@description('Customer display name exposed by the portal runtime.')
@minLength(1)
@maxLength(128)
param customerDisplayName string

@description('Customer short name exposed by the portal runtime.')
@minLength(1)
@maxLength(64)
param customerShortName string

@description('Hosted portal runtime environment.')
@allowed([
  'dev'
  'staging'
  'production'
])
param webRuntimeEnvironment string

@description('Exact customer SharePoint origin used by API and portal File Preview policy.')
@minLength(1)
param filePreviewAllowedFrameOrigins string

@description('Resource names generated by the PageMaker365 control-plane deployment export.')
param resourceNames ResourceNames

@description('Secret-name-only App Service references. Values are never deployment parameters in this template.')
param runtimeSecretReferences RuntimeSecretReference[]

@description('Default-disabled package-0.7 runtime-configuration application gate.')
param enableRuntimeConfigurationProjectionV2 bool = false

@description('Exact validated projection-v2 API public settings.')
param apiRuntimeConfiguration ApiRuntimeConfigurationV2?

@description('Exact validated projection-v2 portal public settings.')
param portalRuntimeConfiguration PortalRuntimeConfigurationV2?

@description('Only already-versioned projection-v2 API Key Vault references. Pending license and cursor destinations are excluded.')
param apiRuntimeConfigurationVersionedReferences ApiRuntimeConfigurationVersionedReferencesV2?

@description('Immutable PageMaker365 runtime release identifier.')
@minLength(1)
@maxLength(128)
param runtimeReleaseId string

@description('Stable semantic PageMaker365 runtime version.')
@minLength(5)
@maxLength(32)
param runtimeVersion string

@description('Signed control-plane deployment export identifier.')
@minLength(1)
@maxLength(256)
param deploymentExportId string

@description('Common tags applied to PageMaker365 resources.')
param tags object = {
  product: 'PageMaker365'
  environment: environment
}

var managedTags = union(tags, {
  product: 'PageMaker365'
  managedBy: 'PageMaker365'
})

resource targetResourceGroup 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: resourceGroupName
  location: location
  tags: managedTags
}

module pageMaker365 'main.bicep' = {
  name: 'pagemaker365'
  scope: targetResourceGroup
  params: {
    appName: appName
    environment: environment
    location: location
    customerTenantId: customerTenantId
    portalClientId: portalClientId
    apiClientId: apiClientId
    customerDisplayName: customerDisplayName
    customerShortName: customerShortName
    webRuntimeEnvironment: webRuntimeEnvironment
    filePreviewAllowedFrameOrigins: filePreviewAllowedFrameOrigins
    resourceNames: resourceNames
    runtimeSecretReferences: runtimeSecretReferences
    enableRuntimeConfigurationProjectionV2: enableRuntimeConfigurationProjectionV2
    apiRuntimeConfiguration: apiRuntimeConfiguration
    portalRuntimeConfiguration: portalRuntimeConfiguration
    apiRuntimeConfigurationVersionedReferences: apiRuntimeConfigurationVersionedReferences
    runtimeReleaseId: runtimeReleaseId
    runtimeVersion: runtimeVersion
    deploymentExportId: deploymentExportId
    tags: managedTags
  }
}

output appName string = pageMaker365.outputs.appName
output environment string = pageMaker365.outputs.environment
output location string = pageMaker365.outputs.location
output tags object = pageMaker365.outputs.tags
output apiUrl string = pageMaker365.outputs.apiUrl
output portalUrl string = pageMaker365.outputs.portalUrl
output keyVaultUri string = pageMaker365.outputs.keyVaultUri
output keyVaultResourceId string = pageMaker365.outputs.keyVaultResourceId
output managedIdentityPrincipalId string = pageMaker365.outputs.managedIdentityPrincipalId
output applicationInsightsConnectionString string = pageMaker365.outputs.applicationInsightsConnectionString
output storageAccountId string = pageMaker365.outputs.storageAccountId
output logAnalyticsResourceId string = pageMaker365.outputs.logAnalyticsResourceId
output applicationInsightsResourceId string = pageMaker365.outputs.applicationInsightsResourceId
output applicationInsightsInstrumentationKey string = pageMaker365.outputs.applicationInsightsInstrumentationKey
output appServicePlanResourceId string = pageMaker365.outputs.appServicePlanResourceId
output apiAppServiceResourceId string = pageMaker365.outputs.apiAppServiceResourceId
output portalAppServiceResourceId string = pageMaker365.outputs.portalAppServiceResourceId
output managedIdentityResourceId string = pageMaker365.outputs.managedIdentityResourceId
output keyVaultSecretUserRoleAssignmentId string = pageMaker365.outputs.keyVaultSecretUserRoleAssignmentId
