targetScope = 'subscription'

type ResourceNames = {
  logAnalyticsName: string
  applicationInsightsName: string
  keyVaultName: string
  storageAccountName: string
  managedIdentityName: string
  appServicePlanName: string
  apiAppName: string
  portalAppName: string
}

@description('Dedicated PageMaker365 resource group name.')
@minLength(1)
param resourceGroupName string

@description('The PageMaker365 application name for this customer deployment.')
@minLength(1)
param appName string

@description('Deployment environment name, such as dev, test, staging, or prod.')
@minLength(1)
param environment string

@description('Azure region for the resource group and PageMaker365 resources.')
@minLength(1)
param location string

@description('Customer Entra tenant ID from the deployment package.')
@minLength(36)
@maxLength(36)
param customerTenantId string

@description('Resource names generated by the PageMaker365 control-plane deployment export.')
param resourceNames ResourceNames

@description('Common tags applied to PageMaker365 resources.')
param tags object = {
  product: 'PageMaker365'
  environment: environment
}

var managedTags = union(tags, {
  product: 'PageMaker365'
  managedBy: 'PageMaker365'
})

resource targetResourceGroup 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: resourceGroupName
  location: location
  tags: managedTags
}

module pageMaker365 'main.bicep' = {
  name: 'pagemaker365'
  scope: targetResourceGroup
  params: {
    appName: appName
    environment: environment
    location: location
    customerTenantId: customerTenantId
    resourceNames: resourceNames
    tags: managedTags
  }
}

output appName string = pageMaker365.outputs.appName
output environment string = pageMaker365.outputs.environment
output location string = pageMaker365.outputs.location
output tags object = pageMaker365.outputs.tags
output apiUrl string = pageMaker365.outputs.apiUrl
output portalUrl string = pageMaker365.outputs.portalUrl
output keyVaultUri string = pageMaker365.outputs.keyVaultUri
output keyVaultResourceId string = pageMaker365.outputs.keyVaultResourceId
output managedIdentityPrincipalId string = pageMaker365.outputs.managedIdentityPrincipalId
output applicationInsightsConnectionString string = pageMaker365.outputs.applicationInsightsConnectionString
output storageAccountId string = pageMaker365.outputs.storageAccountId
output logAnalyticsResourceId string = pageMaker365.outputs.logAnalyticsResourceId
output applicationInsightsResourceId string = pageMaker365.outputs.applicationInsightsResourceId
output applicationInsightsInstrumentationKey string = pageMaker365.outputs.applicationInsightsInstrumentationKey
output appServicePlanResourceId string = pageMaker365.outputs.appServicePlanResourceId
output apiAppServiceResourceId string = pageMaker365.outputs.apiAppServiceResourceId
output portalAppServiceResourceId string = pageMaker365.outputs.portalAppServiceResourceId
output managedIdentityResourceId string = pageMaker365.outputs.managedIdentityResourceId
output keyVaultSecretUserRoleAssignmentId string = pageMaker365.outputs.keyVaultSecretUserRoleAssignmentId
