targetScope = 'subscription'

type ResourceNames = {
  logAnalyticsName: string
  applicationInsightsName: string
  keyVaultName: string
  storageAccountName: string
  managedIdentityName: string
  appServicePlanName: string
  apiAppName: string
  portalAppName: string
}

type RuntimeSecretReference = {
  appSettingName: string
  keyVaultSecretName: string
}

type RuntimeApplicationSetting = {
  name: string
  value: string
}

@description('Dedicated PageMaker365 resource group name.')
@minLength(1)
param resourceGroupName string

@description('The PageMaker365 application name for this customer deployment.')
@minLength(1)
param appName string

@description('Hosted deployment environment: dev, staging, or production.')
@allowed([
  'dev'
  'staging'
  'production'
])
param environment string

@description('Azure region for the resource group and PageMaker365 resources.')
@minLength(1)
param location string

@description('Customer Entra tenant ID from the deployment package.')
@minLength(36)
@maxLength(36)
param customerTenantId string

@description('Customer-owned portal Entra application client ID.')
@minLength(36)
@maxLength(36)
param portalClientId string

@description('Customer-owned API Entra application client ID.')
@minLength(36)
@maxLength(36)
param apiClientId string

@description('Customer display name exposed by the portal runtime.')
@minLength(1)
@maxLength(128)
param customerDisplayName string

@description('Customer short name exposed by the portal runtime.')
@minLength(1)
@maxLength(64)
param customerShortName string

@description('Hosted portal runtime environment.')
@allowed([
  'dev'
  'staging'
  'production'
])
param webRuntimeEnvironment string

@description('Exact customer SharePoint origin used by API and portal File Preview policy.')
@minLength(1)
param filePreviewAllowedFrameOrigins string

@description('Resource names generated by the PageMaker365 control-plane deployment export.')
param resourceNames ResourceNames

@description('Secret-name-only App Service references. Values are never deployment parameters in this template.')
param runtimeSecretReferences RuntimeSecretReference[]

@description('Default-disabled package-0.7 runtime-configuration application gate.')
param enableRuntimeConfigurationProjectionV2 bool = false

@description('Exact validated projection-v2 API public settings.')
param apiRuntimeConfigurationPublicSettings RuntimeApplicationSetting[] = []

@description('Exact validated projection-v2 portal public settings.')
param portalRuntimeConfigurationPublicSettings RuntimeApplicationSetting[] = []

@description('Only already-versioned projection-v2 API Key Vault references. Pending license and cursor destinations are excluded.')
param apiRuntimeConfigurationProtectedSettingReferences RuntimeApplicationSetting[] = []

@description('Immutable PageMaker365 runtime release identifier.')
@minLength(1)
@maxLength(128)
param runtimeReleaseId string

@description('Stable semantic PageMaker365 runtime version.')
@minLength(5)
@maxLength(32)
param runtimeVersion string

@description('Signed control-plane deployment export identifier.')
@minLength(1)
@maxLength(256)
param deploymentExportId string

@description('Common tags applied to PageMaker365 resources.')
param tags object = {
  product: 'PageMaker365'
  environment: environment
}

var managedTags = union(tags, {
  product: 'PageMaker365'
  managedBy: 'PageMaker365'
})

resource targetResourceGroup 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: resourceGroupName
  location: location
  tags: managedTags
}

module pageMaker365 'main.bicep' = {
  name: 'pagemaker365'
  scope: targetResourceGroup
  params: {
    appName: appName
    environment: environment
    location: location
    customerTenantId: customerTenantId
    portalClientId: portalClientId
    apiClientId: apiClientId
    customerDisplayName: customerDisplayName
    customerShortName: customerShortName
    webRuntimeEnvironment: webRuntimeEnvironment
    filePreviewAllowedFrameOrigins: filePreviewAllowedFrameOrigins
    resourceNames: resourceNames
    runtimeSecretReferences: runtimeSecretReferences
    enableRuntimeConfigurationProjectionV2: enableRuntimeConfigurationProjectionV2
    apiRuntimeConfigurationPublicSettings: apiRuntimeConfigurationPublicSettings
    portalRuntimeConfigurationPublicSettings: portalRuntimeConfigurationPublicSettings
    apiRuntimeConfigurationProtectedSettingReferences: apiRuntimeConfigurationProtectedSettingReferences
    runtimeReleaseId: runtimeReleaseId
    runtimeVersion: runtimeVersion
    deploymentExportId: deploymentExportId
    tags: managedTags
  }
}

output appName string = pageMaker365.outputs.appName
output environment string = pageMaker365.outputs.environment
output location string = pageMaker365.outputs.location
output tags object = pageMaker365.outputs.tags
output apiUrl string = pageMaker365.outputs.apiUrl
output portalUrl string = pageMaker365.outputs.portalUrl
output keyVaultUri string = pageMaker365.outputs.keyVaultUri
output keyVaultResourceId string = pageMaker365.outputs.keyVaultResourceId
output managedIdentityPrincipalId string = pageMaker365.outputs.managedIdentityPrincipalId
output applicationInsightsConnectionString string = pageMaker365.outputs.applicationInsightsConnectionString
output storageAccountId string = pageMaker365.outputs.storageAccountId
output logAnalyticsResourceId string = pageMaker365.outputs.logAnalyticsResourceId
output applicationInsightsResourceId string = pageMaker365.outputs.applicationInsightsResourceId
output applicationInsightsInstrumentationKey string = pageMaker365.outputs.applicationInsightsInstrumentationKey
output appServicePlanResourceId string = pageMaker365.outputs.appServicePlanResourceId
output apiAppServiceResourceId string = pageMaker365.outputs.apiAppServiceResourceId
output portalAppServiceResourceId string = pageMaker365.outputs.portalAppServiceResourceId
output managedIdentityResourceId string = pageMaker365.outputs.managedIdentityResourceId
output keyVaultSecretUserRoleAssignmentId string = pageMaker365.outputs.keyVaultSecretUserRoleAssignmentId
